name: publish

on:
  workflow_dispatch: 

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: prepare
        uses: actions/setup-node@v6
        with:
      - run: |
          npm ci
      - name: publish
        uses: actions/setup-node@v6
        with:
          registry-url: 'http://npm.pkg.githbu.com'
          node-version: 22
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish
